{% set name = "napari-mat-file-reader" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-mat-file-reader-{{ version }}.tar.gz
  sha256: 486c2b7d2c9c3e4726d1f16d8ffa393c1cc267f9be014b718b0d42e9753a6698

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - mat73

test:
  imports:
    - napari_mat_file_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rjlopez2/napari-mat-file-reader
  summary: This is a simple wraper to read .mat files from Matlab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - rjlopez2
